### ISSUE TITLE
CartController-Unhandled Event 

### ISSUE THREAD

**Issue by fdaugs** [JuHardtung/WBA2SS16DaugsHardtungPack#1]
Fehler beim abfragen eines nicht bestehenden Warenkorbs nicht abgefangen.

**Comment by JuHardtung** [comment]
Die Möglichkeit des leeren Warenkorbs wird doch abgefangen:

``` javascript
                if (obj == "[]") {
                    res.status(500);
                    res.write('Cart empty!');
                    res.end();
                }
```

Oder meinst du, falls der Warenkorb gar nicht existiert?
Aber das sollte eigentlich nicht möglich sein, da jeder grundsätzlich einen leeren Warenkorb besitzt, dieser aber definitiv existiert.

**Comment by fdaugs** [comment]
Ja das mein ich :D Bin ich nur Bein testen drüber gestolpert...
