### ISSUE TITLE
Datenbankstruktur

### ISSUE THREAD

**Issue by JuHardtung** [JuHardtung/WBA2SS16DaugsHardtungPack#2]
Die Datenbankstruktur wie sie in der database.md liegt bisher garnicht vor.

Bis jetzt werden alle User in einer Liste gespeichert. Jeder Eintrag (jeder User) besteht aus einem JSON String, welcher alle Parameter eines Users enthält.

**Comment by fdaugs** [comment]
Die Datenbankstruktur, wie ich sie dokumentiert hab, wir von mir so benutzt.(AuthController) Das bedeutet es gibt noch einige Redundanzen(addUser, signup) und inkompatibilitäten zwischen den Controllern.

**Comment by JuHardtung** [comment]
Achso, also noch eine Sache die wir fixen müssten

**Comment by JuHardtung** [comment]
Noch ne Frage zu deiner Datenbankstruktur.

In welchem Format wolltest du neue User/Artikel anlegen? Ich hatte das ja bis jetzt so gemacht, dass wir Artikel/User als JSON bekommen und dann in einer Liste speichern. Allerdings hat JSON doch ein falschen Format und kann nicht direkt die Parameter in die HMSET Funktion von Redis einspeisen, oder?

Mann müsste sonst den Inhalt des JSON in einen String parsen und dann die ":" zwischen Key und Inhalt in ein "," umwandeln. Das Format würde dann HMSET annehmen.
