### ISSUE TITLE
Datenbankstruktur mit Hashes ist umständlich

### ISSUE THREAD

**Issue by JuHardtung** [JuHardtung/WBA2SS16DaugsHardtungPack#3]
Ich bin immernoch der Meinung, dass die Datenbankstruktur mit den Hashes alles unnötig verkompliziert. EIn Beispiel:

Wenn wir alle Artikel ausgeben möchten, müssten wir bei der Datenbankstruktur mit Listen nur einen Zweizeiler benutzen.

``` javascript
redisClient.lrange('ARTICLE', 0, -1, function(err, reply) {
});
```

Bei der Struktur mit Hashes müssten wir uns zunächst die Anzahl aller Artikel ausrechnen.
Das wäre mit:

``` javascript
redisClient.hlen('articleListe', function(err, reply){
});
```

Danach müssen wir eine for-Schleife schreiben, die für _"redisClient.hlen"_ den Inhalt des Hashes _"article:?"_ auswirft.

Dazu müssten wir in der for-Schleife erst bei jedem Schleifendurchgang den richtigen String für einen Artikel herausfinden:

``` javascript
var _article = "article:" + i;
```

Danach können wir erst mit

``` javascript
redisClient.hgetall(_article, function(err, reply){
});
```

den Inhalt von jedem einzelnen Artikel bekommen.

Dann haben wir aber erst die 3 einzelnen Artikel. Aber wir können die nicht alle in einen String parsen und in den Body schicken, weil das dann mit der Asynchronität schief geht.
D.h. wir müssten zunächst noch mit irgendwelchen rekursiven Funktionen rumtricksen, damit wir alle Artikel zusammen in den Body bekommen.

Bei z.B. dem Hinzufügen von neuen Artikeln ist es zwar nicht ganz so schlimm, aber für jeden neuen Artikel muss man ja zum einen den eigentlichen Artikel hinzufügen, aber dazu muss man ja noch die _"articleList"_ updaten.

**Comment by fdaugs** [comment]
Ja da könntest du recht haben, ich denke auch, dass es sinnvollist so eine Liste zu haben. Aber wir können dann nicht einfach nur Jsons mit den daten in die Liste packen sondern nur die ids oder so. Weil wenn man keine Struktur hat, die die ID mit den Daten verknüpft kann man die Daten in einem anderen Kontext als "alle ausgeben" nicht abrufen

**Comment by JuHardtung** [comment]
Hmm also hätten wir eine "articleList", welche alle Artikel in der Form enthält:

1) {ID: 1, Name: "Ball", Preis: 3.99}
2) {ID: 2, Name: "Auto", Preis: 4.99}
usw.

So müssten wir immer eine Schleife über alle Elemente von "articleList" drüberlaufen lassen um einen Artikel mit bestimmter ID herauszufinden. Da hätte die Form mit Hashes natürlich einen Vorteil.

ODER:

Wir können die Stelle an denen die Artikel in der Liste gespeichert sind als ID nehmen:
Dann könnte man einen Artikel mit bestimmter ID ganz einfach mit:

``` javascript
lrange articleList 2 2
```

bekommen. Das wäre ein Beispiel für die ID 3, weil eine Redis Liste bei 0 beginnt. 
So hätten wir keine Probleme die IDs zu bekommen, haben nur eine Liste für Artikel und können alle Elemente einfach erreichen.
