### ISSUE TITLE
Wo liegt das problem?

### ISSUE THREAD

**Issue by fdaugs** [JuHardtung/WBA2SS16DaugsHardtungPack#4]
Also ich hab dir das mal gemacht. die funktion in der Datei articleFürJulian gibt alle Artikel aus...
du musst jetzt nur noch sicherstellen, dass sie richtig angelegt werden (express-validate).
Inder Liste articles sind jetzt nur die ids gespeichert und die infos zu Artikeln in `articles:{id} "{jsonstuff}`

**Comment by JuHardtung** [comment]
Ich versteh nur nicht wirklich warum du das so kompliziert haben möchtest. Bei dir muss man ja die Artikelliste verwalten und dazu noch die einzelnen Keys für die Artikel.
Dann kannst du die Artikel auch direkt in der Liste speichern und dir die IDs aus dem JSON holen.
Für den Warenkorb hättest du dann auch einfach eine liste wo die Ids mit der Menge stehen.
Aber von mir aus benutzen wir jetzt einfach die unnötig komplizierte Methode damit wir mal was einheitliches haben.
